# sb2.x 默认数据源Hikari配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wukongnotnull.domain

#分页插件配置
pagehelper:
  helper-dialect: mysql
