server:
  servlet:
    context-path: /zhubajie
  port: 8081


spring:
  mvc:
    static-path-pattern: /wk/** #修改静态资源访问路径
  web:
    resources:
      static-locations:
        classpath:/wukong,classpath:/META-INF/resources,classpath:/static